SET "patchPath=%temp%\CreativeCloudPatcher.ps1"
echo function HexStringToBytes($hex) { >> "%patchPath%"
echo     $bytes = New-Object Byte[] ($hex.Length / 2) >> "%patchPath%"
echo     for ($i = 0; $i -lt $hex.Length; $i += 2) { >> "%patchPath%"
echo         $bytes[$i / 2] = [Convert]::ToByte($hex.Substring($i, 2), 16) >> "%patchPath%"
echo     } >> "%patchPath%"
echo     return $bytes >> "%patchPath%"
echo } >> "%patchPath%"
echo function PatchFile($fileName, $patches) { >> "%patchPath%"
echo     $content = [System.IO.File]::ReadAllBytes($fileName) >> "%patchPath%"
echo     foreach ($patch in $patches) { >> "%patchPath%"
echo         $original = HexStringToBytes $patch[0] >> "%patchPath%"
echo         $patched = HexStringToBytes $patch[1] >> "%patchPath%"
echo         for ($pos = 0; $pos -le $content.Length - $original.Length; $pos++) { >> "%patchPath%"
echo             $found = $true >> "%patchPath%"
echo             for ($j = 0; $j -lt $original.Length; $j++) { >> "%patchPath%"
echo                 if ($content[$pos + $j] -ne $original[$j]) { >> "%patchPath%"
echo                     $found = $false >> "%patchPath%"
echo                     break >> "%patchPath%"
echo                 } >> "%patchPath%"
echo             } >> "%patchPath%"
echo             if ($found) { >> "%patchPath%"
echo                 for ($k = 0; $k -lt $patched.Length; $k++) { >> "%patchPath%"
echo                     $content[$pos + $k] = $patched[$k] >> "%patchPath%"
echo                 } >> "%patchPath%"
echo                 $pos += $original.Length - 1 >> "%patchPath%"
echo             } >> "%patchPath%"
echo         } >> "%patchPath%"
echo     } >> "%patchPath%"
echo     [System.IO.File]::WriteAllBytes($fileName, $content) >> "%patchPath%"
echo } >> "%patchPath%"
echo $filesToPatch = @( >> "%patchPath%"
echo     @{ >> "%patchPath%"
echo         Path = "C:\Program Files (x86)\Common Files\Adobe\Adobe Desktop Common\AppsPanel\AppsPanelBL.dll" >> "%patchPath%"
echo         Patches = @( >> "%patchPath%"
echo             @("0F0085C00F859D000000", "0F00FEC00F859D000000"), >> "%patchPath%"
echo             @("0000E8A1550E0085", "0000E8A1550E00FE"), >> "%patchPath%"
echo             @("0000E89185020085", "0000E891850200FE"), >> "%patchPath%"
echo             @("E883FDFFFF85C00F", "E883FDFFFFFEC00F"), >> "%patchPath%"
echo             @("CEE8F2F7FFFF85C0", "CEE8F2F7FFFFFEC0"), >> "%patchPath%"
echo             @("FF85C00F85760200", "FFFEC00F85760200"), >> "%patchPath%"
echo             @("0083782C000F8495", "00C6402C000F8495"), >> "%patchPath%"
echo             @("010000837844000F", "010000C64044000F"), >> "%patchPath%"
echo             @("848B01000083785C", "848B010000C6405C") >> "%patchPath%"
echo         ) >> "%patchPath%"
echo     }, >> "%patchPath%"
echo     @{ >> "%patchPath%"
echo         Path = "C:\Program Files (x86)\Common Files\Adobe\Adobe Desktop Common\ADS\ContainerBL.dll" >> "%patchPath%"
echo         Patches = @( >> "%patchPath%"
echo             @("0084C00F85890300", "0084C0E98A030000"), >> "%patchPath%"
echo             @("008B35303C2E1085", "908B35303C2E1085") >> "%patchPath%"
echo         ) >> "%patchPath%"
echo     } >> "%patchPath%"
echo ) >> "%patchPath%"
echo foreach ($file in $filesToPatch) { >> "%patchPath%"
echo     $defaultPath = $file.Path >> "%patchPath%"
echo     if (!(Test-Path $defaultPath)) { >> "%patchPath%"
echo         Write-Host "File $defaultPath does not exist. Skipping..." >> "%patchPath%"
echo         continue >> "%patchPath%"
echo     } >> "%patchPath%"
echo     PatchFile $defaultPath $file.Patches >> "%patchPath%"
echo } >> "%patchPath%"
rem Run the powershell script
powershell -ExecutionPolicy Bypass -File "%temp%\CreativeCloudPatcher.ps1"
echo Patching! This may take a while...
echo.
echo Files patched!
echo.
